add intermediate build step for amis

diff --git a/deploy/templates/carnivore b/deploy/templates/carnivore
--- a/deploy/templates/carnivore
+++ b/deploy/templates/carnivore
@@ -41,6 +41,12 @@ mv $HOME/app/server/deploy/env/.env.$NODE_ENV.json $HOME/app/server/.env.json
 mv $HOME/app/precache/node_modules $HOME/app/server/node_modules
 npm install --prefix $HOME/app/server --production
 
+if [ $? -ne 0 ]
+then
+  echo "packer: npm install failed. bailing"
+  exit 1
+fi
+
 PORT=3000
 
 echo "packer: booting appserver daemon..."
diff --git a/deploy/templates/primal b/deploy/templates/primal
--- a/deploy/templates/primal
+++ b/deploy/templates/primal
@@ -1,20 +1,5 @@
 #!/bin/bash
 
-echo "packer: updating aptitude"
-sudo apt-key update
-sudo apt-get update
-sudo apt-get remove apt-listchanges -y
-sudo apt-get install git make g++ graphicsmagick curl python-software-properties software-properties-common lsof libkrb5-dev -y
-sudo add-apt-repository ppa:nginx/stable -y
-
-echo "packer: creating swap space"
-sudo mkdir -p /media/fasthdd
-sudo dd if=/dev/zero of=/media/fasthdd/swapfile.img bs=1024 count=3M
-sudo mkswap /media/fasthdd/swapfile.img
-sudo chmod 0600 /media/fasthdd/swapfile.img
-echo "/media/fasthdd/swapfile.img swap swap sw 0 0" | sudo tee -a /etc/fstab
-sudo swapon /media/fasthdd/swapfile.img
-
 echo "packer: nginx"
 sudo mkdir -p /var/log/nginx
 sudo chown $INSTANCE_USER /var/log/nginx
@@ -23,29 +8,6 @@ sudo apt-get install nginx -y
 
 echo "packer: nginx as a service"
 sudo update-rc.d nginx defaults
-
-echo "packer: tweaking tcp"
-sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0
-sudo sysctl -w net.ipv4.tcp_window_scaling=1
-
-echo "packer: ipv4 forwarding"
-cp /etc/sysctl.conf /tmp/
-echo "net.ipv4.ip_forward = 1" >> /tmp/sysctl.conf
-sudo cp /tmp/sysctl.conf /etc/
-sudo sysctl -p /etc/sysctl.conf
-
-echo "packer: forward port 80 to 8080"
-sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
-sudo iptables -A INPUT -p tcp -m tcp --sport 80 -j ACCEPT
-sudo iptables -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT
-sudo iptables-save > /tmp/iptables-store.conf
-sudo mv /tmp/iptables-store.conf /etc/iptables-store.conf
-
-echo "packer: remember port forwarding rule across reboots"
-echo "#!/bin/sh" > /tmp/iptables-ifupd
-echo "iptables-restore < /etc/iptables-store.conf" >> /tmp/iptables-ifupd
-chmod +x /tmp/iptables-ifupd
-sudo mv /tmp/iptables-ifupd /etc/network/if-up.d/iptables
 
 echo "packer: nvm"
 curl https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | bash
@@ -63,3 +25,9 @@ mkdir -p $HOME/app/precache
 cp -r /tmp/mailtube $HOME/app/mailtube
 cp $HOME/app/mailtube/package.json $HOME/app/precache
 npm install --prefix $HOME/app/precache --production
+
+if [ $? -ne 0 ]
+then
+  echo "packer: npm install failed. bailing"
+  exit 1
+fi
