rm versioning, faster deployments

diff --git a/build/ec2/deploy b/build/ec2/deploy
--- a/build/ec2/deploy
+++ b/build/ec2/deploy
@@ -12,20 +12,16 @@ INSTANCE_ID=$(cat $KEYFILE.id)
 PUBLIC_DNS=$(cat $KEYFILE.dns)
 
 APP="~/apps/$ENV"
-APP_VERSIONS="$APP/v"
-APP_LIVE="$APP/live"
 APP_CONFIG="$APP/config"
 RSYNC="~/apps/.rsync/$ENV"
 RSYNC_MAILTUBE="$RSYNC/mailtube"
-RSYNC_REPO="$RSYNC/app/"
+RSYNC_REPO="$RSYNC/app"
 
 # bump package.json
 git add .
 git commit -am "Pre-deploy commit because $EMOJI"
 npm version patch -m "Upgrade to %s because deploy $EMOJI"
 VERSION=$(cat package.json | jq -r .version)
-
-APP_LATEST="$APP_VERSIONS/$VERSION"
 
 # build distribution
 npm run build-$ENV
@@ -38,7 +34,7 @@ rsync \
   --exclude-from .rsyncignore \
   -e "ssh -i $KEYFILE -o StrictHostKeyChecking=no" \
   . \
-  $INSTANCE_USER@$PUBLIC_DNS:$RSYNC_REPO
+  $INSTANCE_USER@$PUBLIC_DNS:$RSYNC_REPO/
 
 # jump into instance
 ssh -Ti $KEYFILE -o StrictHostKeyChecking=no $INSTANCE_USER@$PUBLIC_DNS << EOF_DEPLOY
@@ -48,37 +44,30 @@ ssh -Ti $KEYFILE -o StrictHostKeyChecking=no $INSTANCE_USER@$PUBLIC_DNS << EOF_D
     sed -i "s#{NAME}#$NAME#g" $APP/$NAME.conf
     sed -i "s#{USER}#$INSTANCE_USER#g" $APP/$NAME.conf
     sed -i "s#{NODE_BIN}#\$NVM_BIN/node#g" $APP/$NAME.conf
-    sed -i "s#{APP_SCRIPT}#\$HOME/apps/$ENV/live/cluster.js#g" $APP/$NAME.conf
+    sed -i "s#{APP_SCRIPT}#\$HOME/apps/.rsync/$ENV/app/cluster.js#g" $APP/$NAME.conf
     sudo cp $APP/$NAME.conf /etc/init/$NAME.conf
     rm $APP/$NAME.conf
     sudo start $NAME
   }
 
   cluster_start_or_reload () {
-    cat $APP/.pid
+    cat $RSYNC_REPO/.pid
     if [ "\$?" == "0" ] ; then
       echo "Reloading cluster..."
-      kill -s SIGUSR2 \$(cat $APP/.pid) || (echo "Reload failed..." && rm $APP/.pid && cluster_start)
+      kill -s SIGUSR2 \$(cat $RSYNC_REPO/.pid) || (echo "Reload failed..." && rm $RSYNC_REPO/.pid && cluster_start)
     else
       cluster_start
     fi
   }
 
-  rm -rf $APP_LATEST
-  cp -r $RSYNC_REPO $APP_LATEST
-  cp -r $APP_VERSIONS/\$(ls -t1 $APP_VERSIONS | sort --version-sort -r | head -2 | tail -1)/node_modules $APP_LATEST
-  cp $APP_LATEST/package.json $APP/package.json
-  ln -sfn $APP_LATEST $APP_LIVE
-  ln -sfn $APP_CONFIG $APP_LATEST/.env
-  find $APP_VERSIONS -mindepth 1 -maxdepth 1 | sort --version-sort -r | tail -n +6 | xargs rm -rf
-  npm --prefix $APP_LATEST prune
-  npm --prefix $APP_LATEST install --production --no-optional
+  ln -sfn $APP_CONFIG $RSYNC_REPO/.env
+  npm --prefix $RSYNC_REPO prune
+  npm --prefix $RSYNC_REPO install --production --no-optional
   sudo nginx -s reload || sudo service nginx start || (sudo cat /var/log/nginx/error.log && exit 1)
   cluster_start_or_reload
 
   # cron job every 5 minutes
-  chmod +x $APP_LIVE/jobs/scheduler
-  (crontab -l ; echo "*/5 * * * * . \$HOME/.nvm/nvm.sh; $APP_LIVE/jobs/scheduler") | sort - | uniq - | crontab -
+  (crontab -l ; echo "*/5 * * * * . \$HOME/.nvm/nvm.sh; $RSYNC_REPO/jobs/scheduler") | sort - | uniq - | crontab -
 
 EOF_DEPLOY
 
