Pre-deploy commit because :sailboat:

diff --git a/build/ec2/deploy b/build/ec2/deploy
--- a/build/ec2/deploy
+++ b/build/ec2/deploy
@@ -36,40 +36,40 @@ rsync \
   . \
   $INSTANCE_USER@$PUBLIC_DNS:$RSYNC_REPO/
 
-# jump into instance
-ssh -Ti $KEYFILE -o StrictHostKeyChecking=no $INSTANCE_USER@$PUBLIC_DNS << EOF_DEPLOY
-  cluster_start () {
-    echo "Initializing cluster..."
-    cp $RSYNC_MAILTUBE/upstart/app.conf $APP/$NAME.conf
-    sed -i "s#{NAME}#$NAME#g" $APP/$NAME.conf
-    sed -i "s#{USER}#$INSTANCE_USER#g" $APP/$NAME.conf
-    sed -i "s#{NODE_BIN}#\$NVM_BIN/node#g" $APP/$NAME.conf
-    sed -i "s#{APP_SCRIPT}#\$HOME/apps/.rsync/$ENV/app/cluster.js#g" $APP/$NAME.conf
-    sudo cp $APP/$NAME.conf /etc/init/$NAME.conf
-    rm $APP/$NAME.conf
-    sudo start $NAME
-  }
+# # jump into instance
+# ssh -Ti $KEYFILE -o StrictHostKeyChecking=no $INSTANCE_USER@$PUBLIC_DNS << EOF_DEPLOY
+#   cluster_start () {
+#     echo "Initializing cluster..."
+#     cp $RSYNC_MAILTUBE/upstart/app.conf $APP/$NAME.conf
+#     sed -i "s#{NAME}#$NAME#g" $APP/$NAME.conf
+#     sed -i "s#{USER}#$INSTANCE_USER#g" $APP/$NAME.conf
+#     sed -i "s#{NODE_BIN}#\$NVM_BIN/node#g" $APP/$NAME.conf
+#     sed -i "s#{APP_SCRIPT}#\$HOME/apps/.rsync/$ENV/app/cluster.js#g" $APP/$NAME.conf
+#     sudo cp $APP/$NAME.conf /etc/init/$NAME.conf
+#     rm $APP/$NAME.conf
+#     sudo start $NAME
+#   }
 
-  cluster_start_or_reload () {
-    cat $RSYNC_REPO/.pid
-    if [ "\$?" == "0" ] ; then
-      echo "Reloading cluster..."
-      kill -s SIGUSR2 \$(cat $RSYNC_REPO/.pid) || (echo "Reload failed..." && rm $RSYNC_REPO/.pid && cluster_start)
-    else
-      cluster_start
-    fi
-  }
+#   cluster_start_or_reload () {
+#     cat $RSYNC_REPO/.pid
+#     if [ "\$?" == "0" ] ; then
+#       echo "Reloading cluster..."
+#       kill -s SIGUSR2 \$(cat $RSYNC_REPO/.pid) || (echo "Reload failed..." && rm $RSYNC_REPO/.pid && cluster_start)
+#     else
+#       cluster_start
+#     fi
+#   }
 
-  ln -sfn $APP_CONFIG $RSYNC_REPO/.env
-  ln -sfn $RSYNC_REPO $APP/live
-  npm --prefix $RSYNC_REPO prune
-  npm --prefix $RSYNC_REPO install --production --no-optional
-  sudo nginx -s reload || sudo service nginx start || (sudo cat /var/log/nginx/error.log && exit 1)
-  cluster_start_or_reload
+#   ln -sfn $APP_CONFIG $RSYNC_REPO/.env
+#   ln -sfn $RSYNC_REPO $APP/live
+#   npm --prefix $RSYNC_REPO prune
+#   npm --prefix $RSYNC_REPO install --production --no-optional
+#   sudo nginx -s reload || sudo service nginx start || (sudo cat /var/log/nginx/error.log && exit 1)
+#   cluster_start_or_reload
 
-  # cron job every 5 minutes
-  (crontab -l ; echo "*/5 * * * * . \$HOME/.nvm/nvm.sh; $RSYNC_REPO/jobs/scheduler") | sort - | uniq - | crontab -
+#   # cron job every 5 minutes
+#   (crontab -l ; echo "*/5 * * * * . \$HOME/.nvm/nvm.sh; $RSYNC_REPO/jobs/scheduler") | sort - | uniq - | crontab -
 
-EOF_DEPLOY
+# EOF_DEPLOY
 
-echo "Deployed v$VERSION to $ENV"
+# echo "Deployed v$VERSION to $ENV"
